## 1. Importing Numpy module
Numpy is imported by the alias np

In [2]:
import numpy as np

## 2. Creating Numpy Arrays
There are several ways to create Numpy arrays

In [3]:
# Method 1: From Python list
arr1 = np.array([1, 2, 3, 4, 5])
print("From list:", arr1)

# Method 2: Using np.arrange() - similar to range()
arr2 = np.arange(0, 10, 2) # start, stop(not included), step
print("Using arrange:", arr2)

# Method 3: Using np.linspace() - evenly spaced numbers
arr3 = np.linspace(0, 1, 5) # start, stop, number of elements
print("Using linspace:", arr3)

# Method 4: Creating arrays of zeros
zeros = np.zeros(5)
print("Zeros:", zeros)

# Method 5: Creating arrays of ones
ones = np.ones(5)
print("Ones:", ones)

# Method 6: Creating arrays with specific values
full = np.full(5, 7) # shape, fill_value
print("Full (all 7s):", full)

# Method 7: Identity matrix
identity = np.eye(3)
print("Identity matrix:\n", identity)

# Method 8: Random arrays
random_arr = np.random.rand(5) # Uniform distribution [0, 1]
print("Random (uniform):", random_arr)

random_int = np.random.randint(1, 10, size=5) # [low, high], size
print("Random integers:", random_int)

From list: [1 2 3 4 5]
Using arrange: [0 2 4 6 8]
Using linspace: [0.   0.25 0.5  0.75 1.  ]
Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Full (all 7s): [7 7 7 7 7]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random (uniform): [0.55271791 0.77363862 0.56591855 0.38452523 0.01555956]
Random integers: [1 9 7 3 3]


## 3. NumPy Data Types (dtype)
NumPy arrays are homogeneous -all elements have the same type. Types affect memory usage and operations

In [4]:
# Type inference and common types
arr_int = np.array([1, 2, 3])
arr_float = np.array([1.0, 2.0, 3.5])
arr_mix = np.array([1, 2,5, 3])

print(f"Array: {arr_int}, Interger: {arr_int.dtype}")
print(f"Array: {arr_float}, Float: {arr_float.dtype}")
print(f"Array: {arr_mix}, Mixed: {arr_mix.dtype}")

# Specifying types
arr1 = np.array([1, 2, 3], dtype=float)
arr2 = arr_int.astype(np.float64) # Convert types

print(f"Specified {arr1} float32: {arr1.dtype}")
print(f"Converted {arr2} to float64: {arr2.dtype}\n")

# Common types: int32, int64, float32, float64, bool
print("Memory: int32/float32 = 4 bytes, int64/float64 = 8 bytes per element")

Array: [1 2 3], Interger: int64
Array: [1.  2.  3.5], Float: float64
Array: [1 2 5 3], Mixed: int64
Specified [1. 2. 3.] float32: float64
Converted [1. 2. 3.] to float64: float64

Memory: int32/float32 = 4 bytes, int64/float64 = 8 bytes per element


## 4. Multi-dimensional Arrays

In [20]:
# 2D array (matrix)
matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array (Matrix)")
print(matrix_2d)
print(f"Shape: {matrix_2d.shape}") # (rows, columns)
print(f"Dimensions: {matrix_2d.ndim}") # Number of dimensions
print(f"Size: {matrix_2d.size}") # Total Number of elements
print(f"Data type: {matrix_2d.dtype}") # Data type of elements

#  3D array
matrix_3d = np.array([[[1, 2], [3, 4]], [[5,6], [7, 8]]])
print("\n3D Array:")
print(matrix_3d)
print(f"Shape: {matrix_3d.shape}") # (depth, rows, columns)
print(f"Dimensions : {matrix_3d.ndim}") # Number of dimesions

# Creating multi-dimensional arrays with specific shapes
zeros_2d = np.zeros(shape=(2, 3, 4), dtype=int) # 3 rows, 4 columns
print("\n2D zeros array:")
print(zeros_2d)
print(f"Shape: {zeros_2d.shape}")
print(f"Dimensions: {zeros_2d.ndim}")

ones_3d = np.ones((2, 2, 4)) # 2 by 3 by 4 array
print("\n3d ones")
print(ones_3d)
print(f"\n3D ones array shape: {ones_3d.shape}")

2D Array (Matrix)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Size: 9
Data type: int64

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions : 3

2D zeros array:
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
Shape: (2, 3, 4)
Dimensions: 3

3d ones
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

3D ones array shape: (2, 2, 4)


## 5. Array Attrubutes and Information
Understanding array properties is crucial for working with NumPy

In [23]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Array")
print(arr)
print(f"\nShape: {arr.shape}")
print(f"Size: {arr.size}") # Total number of elements
print(f"ndim: {arr.ndim}") # Number of dimensions
print(f"dtype: {arr.dtype}") # Data type
print(f"itemsize: {arr.itemsize}") # Size of each element
print(f"nbytes: {arr.nbytes} bytes") # Total memory used
print(f"T (transpose): \n{arr.T}") # Transpose of the array

Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape: (3, 4)
Size: 12
ndim: 2
dtype: int64
itemsize: 8
nbytes: 96 bytes
T (transpose): 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


## 6. Indexing and Slicing
Accessing and modifying array elements is similar to Python lists, but more powerful

In [26]:
arr = np.array([10, 20, 30, 40, 50])

# 1D indexing (same as Python lists)
print("Original array:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Elements 1 to 3:", arr[1:4]) # slicing: [start:stop:step]
print("Every other elements:", arr[::2])

# 2D indexing
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(matrix)
print("Element at row 1, column 2:", matrix[1, 2]) # Row, Column
print("First row:", matrix[0, :]) # All columns of first row
print("Second column:", matrix[:, 1]) # All rows of second column
print("Submatrix {first 2 rows, first 2 columns}:")
print(matrix[0:2, 0:2])

# Boolean indexing - powerful feature!
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("\n--- Boolean Indexing ---")
print("Original:", arr)
print("Elements greater than 5:", arr[arr > 5])
print("Even numbers:", arr[arr % 2 == 0])

Original array: [10 20 30 40 50]
First element: 10
Last element: 50
Elements 1 to 3: [20 30 40]
Every other elements: [10 30 50]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 6
First row: [1 2 3]
Second column: [2 5 8]
Submatrix {first 2 rows, first 2 columns}:
[[1 2]
 [4 5]]

--- Boolean Indexing ---
Original: [ 1  2  3  4  5  6  7  8  9 10]
Elements greater than 5: [ 6  7  8  9 10]
Even numbers: [ 2  4  6  8 10]
