## Numpy Fundementals

# Introduction to Numpy

In [10]:
import numpy as np

In [11]:
arr = np.array([1, 2, 3, 4, 5])

In [12]:
arr

array([1, 2, 3, 4, 5])

In [13]:
type(arr)

numpy.ndarray

# Checking NumPy Version

The version string is stored under `__version__` attribute

In [14]:
np.__version__

'2.1.3'

# NumPy Creating Arrays
## Create a NumPy ndarray Object

NumPy is used to work with arrays. The array object in NumPy is called `ndarray`.

We can create a NumPy `ndarray` object by using the `array()` function

In [16]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [17]:
type(arr)

numpy.ndarray

To create an `ndarray`, we can pass a list, tuple or any array-like object into the `array()` method, and it will be converted into an `ndarray`

In [18]:
# Passing a tuple
arr = np.array((1, 2, 3, 4))
arr

array([1, 2, 3, 4])

# Dimensions in Arrays

A dimesion in arrays is one level of array depth (nested arrays)

In [19]:
# O-D arrays
arr = np.array(42)
arr

array(42)

In [20]:
# 1-D Array
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [21]:
# 2-D Array
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# 3-D Array
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
])
arr

array([[[1, 2, 3],
        [4, 5, 6]]])

In [23]:
arr.shape

(1, 2, 3)

## Check Number of Dimensions?
NumPy Arrays provides the `ndim` attribute that returns an integer that tells us how many dimensions the array have

In [24]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])

In [25]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays
An array can have any number of dimensions

When the array is created, you can define the number of dimensions by using the `ndim` argument

In [26]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
